export const LOAD_PATIENTS_SUCCESS="LOAD_PATIENTS_SUCCESS";
export const PATIENTS_LISTED_SUCCESS="PATIENTS_LISTED_SUCCESS";
export const PATIENT_CURRENT_LOADED_SUCCESS="PATIENT_CURRENT_LOADED_SUCCESS";

export const PATIENTS_CHANGE_PAGE="PATIENTS_CHANGE_PAGE";
export const UNLOAD_PATIENT="UNLOAD_PATIENT";
export const PATIENTS_SAVED_SUCCESS  = "PATIENTS_SAVED_SUCCESS";

export const INCREMENT_COUNT="INCREMENT_COUNT";
export const DECREMENT_COUNT="DECREMENT_COUNT";
export const RESET_COUNT="RESET_COUNT";
export const VALIDATION_CLEAR="VALIDATION_CLEAR";
export const VALIDATION_SET="VALIDATION_SET";

export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGOUT_SUCCESS="LOGOUT_SUCCESS"

export const BEGIN_API_CALL="BEGIN_API_CALL";
export const API_CALL_ERROR="API_CALL_ERROR";
export const ERROR_CLEAR="ERROR_CLEAR";
export const ERROR_SET ="ERROR_SET";
export const MEDICINES_LISTED_SUCCESS="MEDICINES_LISTED_SUCCESS";
export const PRESCRIPTION_SAVED_SUCCESS="PRESCRIPTION_SAVED_SUCCESS";


export const PRESCRIPTION_LOAD_CURRENT="PRESCRIPTION_LOAD_CURRENT";
export const PRESCRIPTION_UNLOAD_CURRENT="PRESCRIPTION_UNLOAD_CURRENT";
