export const LOAD_PATIENTS_SUCCESS="LOAD_PATIENTS_SUCCESS";
export const INCREMENT_COUNT="INCREMENT_COUNT";
export const DECREMENT_COUNT="DECREMENT_COUNT";
export const RESET_COUNT="RESET_COUNT";
export const PATIENTS_LISTED_SUCCESS="PATIENTS_LISTED_SUCCESS";
export const PATIENTS_CHANGE_PAGE="PATIENTS_CHANGE_PAGE";
